-- 1. 제품별 공정 수순 정보 및 재공 정보
CREATE TABLE WIP_INFO (
    PLAN_PROD_KEY VARCHAR2(50),
    OPER_ID VARCHAR2(50),
    OPER_SEQ NUMBER,
    WIP_QTY NUMBER,
    CONSTRAINT PK_WIP_INFO PRIMARY KEY (PLAN_PROD_KEY, OPER_ID)
);

-- 2. 제품별 공정별 장비 모델별 시간당 생산량
CREATE TABLE UPH_INFO (
    PLAN_PROD_KEY VARCHAR2(50),
    OPER_ID VARCHAR2(50),
    EQP_MODEL_CD VARCHAR2(50),
    UPH NUMBER,
    CONSTRAINT PK_UPH_INFO PRIMARY KEY (PLAN_PROD_KEY, OPER_ID, EQP_MODEL_CD)
);

-- 3. 제품별 공정별 장비 모델별 시간대별 댓수
CREATE TABLE EQP_QTY_INFO (
    BATCH_ID VARCHAR2(50),
    EQP_MODEL_CD VARCHAR2(50),
    TIME_SLOT VARCHAR2(20), -- e.g., '2026051707'
    EQP_QTY NUMBER,
    CONSTRAINT PK_EQP_QTY_INFO PRIMARY KEY (BATCH_ID, EQP_MODEL_CD, TIME_SLOT)
);

-- 5. 제품별 공정별 장비 모델별 처리가능여부
CREATE TABLE AVAIL_INFO (
    PLAN_PROD_KEY VARCHAR2(50),
    OPER_ID VARCHAR2(50),
    EQP_MODEL_CD VARCHAR2(50),
    AVAIL_YN VARCHAR2(1),
    CONSTRAINT PK_AVAIL_INFO PRIMARY KEY (PLAN_PROD_KEY, OPER_ID, EQP_MODEL_CD)
);

-- 6. Tool 교체 단위 정보 (Batch_ID N:1 매핑)
CREATE TABLE BATCH_TOOL_INFO (
    BATCH_ID VARCHAR2(50),
    PLAN_PROD_KEY VARCHAR2(50),
    OPER_ID VARCHAR2(50),
    CONSTRAINT PK_BATCH_TOOL_INFO PRIMARY KEY (PLAN_PROD_KEY, OPER_ID)
);

-- 7. Tool 갯수 정보
CREATE TABLE TOOL_QTY_INFO (
    BATCH_ID VARCHAR2(50),
    EQP_MODEL_CD VARCHAR2(50),
    TOOL_QTY NUMBER,
    CONSTRAINT PK_TOOL_QTY_INFO PRIMARY KEY (BATCH_ID, EQP_MODEL_CD)
);

-- 8. 계획 정보
CREATE TABLE PLAN_INFO (
    PLAN_PROD_KEY VARCHAR2(50),
    OPER_ID VARCHAR2(50),
    START_TIME VARCHAR2(20),
    END_TIME VARCHAR2(20),
    PLAN_QTY NUMBER
);

-- Output 결과물 테이블
CREATE TABLE RTD_CONV_INF (
    RULE_TIMEKEY VARCHAR2(20),
    FROM_BATCH VARCHAR2(50),
    FROM_PLAN_PROD_KEY VARCHAR2(50),
    FROM_OPER_ID VARCHAR2(50),
    EQP_MODEL_CD VARCHAR2(50),
    TO_BATCH_ID VARCHAR2(50),
    TO_PLAN_PROD_KEY VARCHAR2(50),
    TO_OPER_ID VARCHAR2(50),
    START_CONV_TIME VARCHAR2(20),
    EQP_QTY NUMBER
);

CREATE TABLE RTD_CONV_HI AS SELECT * FROM RTD_CONV_INF WHERE 1=0;

-- 더미 데이터 삽입 스크립트 예시
INSERT INTO WIP_INFO VALUES ('P1', 'OP10', 10, 1000);
INSERT INTO WIP_INFO VALUES ('P2', 'OP10', 10, 500);

INSERT INTO UPH_INFO VALUES ('P1', 'OP10', 'MODEL_A', 100);
INSERT INTO UPH_INFO VALUES ('P1', 'OP10', 'MODEL_B', 120);
INSERT INTO UPH_INFO VALUES ('P2', 'OP10', 'MODEL_A', 80);

INSERT INTO BATCH_TOOL_INFO VALUES ('B1', 'P1', 'OP10');
INSERT INTO BATCH_TOOL_INFO VALUES ('B2', 'P2', 'OP10');

INSERT INTO EQP_QTY_INFO VALUES ('B1', 'MODEL_A', '2026051707', 5);
INSERT INTO EQP_QTY_INFO VALUES ('B2', 'MODEL_A', '2026051707', 3);

INSERT INTO AVAIL_INFO VALUES ('P1', 'OP10', 'MODEL_A', 'Y');
INSERT INTO AVAIL_INFO VALUES ('P1', 'OP10', 'MODEL_B', 'Y');
INSERT INTO AVAIL_INFO VALUES ('P2', 'OP10', 'MODEL_A', 'Y');

INSERT INTO TOOL_QTY_INFO VALUES ('B1', 'MODEL_A', 10);
INSERT INTO TOOL_QTY_INFO VALUES ('B2', 'MODEL_A', 5);

INSERT INTO PLAN_INFO VALUES ('P1', 'OP10', '2026051707', '2026051708', 400);
INSERT INTO PLAN_INFO VALUES ('P2', 'OP10', '2026051707', '2026051708', 200);

COMMIT;
